################### CONFIG Configuration ##########################
server.port=8009
server.servlet.context-path=/api

## App Reinitialisation
app.data-init.enabled=true
app.data-init.reset-before-init=true

################### POSTGRES JPA Configuration ##########################
spring.datasource.url=jdbc:postgresql://localhost:5432/conso_epargne_v2
spring.datasource.username=postgres
spring.datasource.password=Desire01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.leak-detection-threshold=60000

##Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

################### JAVAMAIL Configuration ##########################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=project.consoepargne@gmail.com
spring.mail.password=vdmi vqba goac bylh
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

conso.admin.mail=jeannoelromaricano@gmail.com

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.firebase-configuration-file=project-consoepargne-firebase-adminsdk-q7gzc-9d43cd7217.json

# nowallet properties
nowallet.api.url=https://nowallet-api.mpayment.africa/nowallet/api/v3
nowallet.api.client-id=edispo
nowallet.api.client-secret=BIuGzKR3QaGVkzncBDiKgkOYqC9hXEFr
nowallet.api.om-token=0140cad35d98c04439e13bc956f9d7c3a6c75596640edfbe0987d2cb4019672de0bee3940154c145334ea869440a24af8a944f3708299fe69ed8f08318687bd90925cd652378a482628731d87475a637544de74704cdcd652b2760fdcc35ceb6
nowallet.api.mtn-token=0140cad35d98c04439e13bc956f9d7c3a6c75596640edfbe0987d2cb4019672de0bee3940154c145334ea869440a24af8a944f3708299fe69ed8f08318687bd90925cd652378a482628731d87475a63791e552473355c3598dabd712d1fdcf87
nowallet.api.moov-token=0140cad35d98c04439e13bc956f9d7c3a6c75596640edfbe0987d2cb4019672de0bee3940154c145334ea869440a24af8a944f3708299fe69ed8f08318687bd90925cd652378a482628731d87475a6374f1ab927434dc51027b7e46cf2b1adc2

nowallet.webhook.secret-key=nowallet_sk_9weEgKk1UNXVd7+fJIuiOkGfary651ORVsUtUFmlTxo=
nowallet.webhook.unique-key=nowallet_uk_vmjYQCCsC73h2WRVGJfKuBBVyJ8QjXKxwQpPTIXpfkY=

# Feign Configuration
feign.httpclient.enabled=true

# Dilaac Config.
dilaac.host.url=https://api.dilaac.com
dilaac.project.id=646ddb6194741a6e6f11935e
dilaac.user.email=augustedaya@gmail.com
dilaac.user.password=Conso@2023@
dilaac.client.id=dilaac

# Wave Config.
wave.api.url=https://api.wave.com/v1
wave.api.name=wave-client
wave.api.key=wave_ci_prod_jkhYNAVC_t9kdkfxZzn9GKItJi_Mns4G5LaMwzx3i3Z4--3F3lUSmH6eNS7eN_SylPBNQt_U4YMJhyATLCkwkNRZMY0YPrAxkg
wave.api.key-payout=wave_ci_prod_CYqXcE3gkbLuljJESptmujqT89ABGg27GgoXbnirdPZ7l60dxUHyYshSxKXRJ-vFd4LM6eGwpd12Zt-_x8jb2FsH3KQ_qabMHQ
wave.webhook.secret=WH_WCN8DJH6d6QH

# Paystack Config.
paystack.api.base-url=https://api.paystack.co
paystack.api.secret-key=${PAYSTACK_SECRET_KEY:sk_test_84a1a3286338da1421485de4f4a3017a4970073f}
paystack.api.public-key=${PAYSTACK_PUBLIC_KEY:pk_test_761d4c3be27b086a1bfa3595a029012c0f001e54}
paystack.api.webhook-secret=${PAYSTACK_WEBHOOK_SECRET:votre_secret}
paystack.api.timeout=5000

# Feign Configuration for Paystack
feign.client.config.paystackClient.connectTimeout=5000
feign.client.config.paystackClient.readTimeout=10000
feign.client.config.paystackClient.loggerLevel=full


# Wane Delivery Config.
wane.delivery.api.url=https://groupewanegodwin.com/api/v1/partners
wane.delivery.api.partner-id=lea
wane.delivery.api.vehicule-type=1187682c-aa59-46fb-8fa0-119fc3592fe8
wane.delivery.api.token=425|PXogqR6eRLsGRmvcx6gnZ1K5d8UFPc5Goxy6tdqj4abcdfcb

#Minio config
storage.type=minio
minio.base-url=http://localhost
minio.port=9000
minio.access-key=admin
minio.secret-key=admin_123
minio.bucket-name=conso-epargne
minio.secure=false

# enabled | disabled
app.authentication.country-based=disabled

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always


jwt.secret=ConsoEpargneAppDev_Wizigoth_Zabad.JZs1299X
jwt.expiration-ms=259200000