spring.application.name=conso-epargne-api
spring.main.allow-bean-definition-overriding=true

# Data initialization Configuration
app.data-init.urls.data=classpath:config/data.json
app.data-init.urls.parameters=classpath:config/parameters.json
app.data-init.urls.countries=classpath:config/countries.json
app.data-init.urls.localities=classpath:config/localities.json
app.data-init.urls.districts=classpath:config/districts.json
app.data-init.urls.templates=classpath:config/transaction_message_templates.json

# Quartz config
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.jdbc.schema=classpath:quartz_table_init.sql

# Management config
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Sheduling Pool
spring.task.scheduling.pool.size=5

# Cache Config
cache.config.expiration-minutes=5

# Server Configuration
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.error.whitelabel.enabled=false
server.compression.enabled=true
server.error.path=/error
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
server.compression.min-response-size=2048

# SMS Panel (YellikaSMS) Configuration
yellika.sms.url=https://panel.yellikasms.com
yellika.sms.token=515|V9pxoE9pEgDhkF7s4Y8GgnusRgBxArGwats21Hcp3aae307b

# Conso Epargne Link Configuration
conso.epargne.base-url=https://consoepargneapp.page.link/?apn=com.consoepargne.app&ibi=com.consoepargne.app&link=https://consoepargneapp.page.link
conso.epargne.success-url=${conso.epargne.base-url}/code-success
conso.epargne.failed-url=${conso.epargne.base-url}/code-fail

# Configuration SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.packages-to-scan=com.app.conso_epargne.admin
springdoc.paths-to-match=/api/v1/**

# Personnalisation de la documentation
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.version=openapi_3_0